version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
